//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 10:54:28 PM EST 
//

package org.xml_cml.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.xml_cml.schema package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _PeakList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "peakList");
	private final static QName _Formula_QNAME = new QName(
			"http://www.xml-cml.org/schema", "formula");
	private final static QName _BondType_QNAME = new QName(
			"http://www.xml-cml.org/schema", "bondType");
	private final static QName _Lattice_QNAME = new QName(
			"http://www.xml-cml.org/schema", "lattice");
	private final static QName _Fragment_QNAME = new QName(
			"http://www.xml-cml.org/schema", "fragment");
	private final static QName _Kpoint_QNAME = new QName(
			"http://www.xml-cml.org/schema", "kpoint");
	private final static QName _BasisSet_QNAME = new QName(
			"http://www.xml-cml.org/schema", "basisSet");
	private final static QName _TableHeader_QNAME = new QName(
			"http://www.xml-cml.org/schema", "tableHeader");
	private final static QName _Bond_QNAME = new QName(
			"http://www.xml-cml.org/schema", "bond");
	private final static QName _Eigen_QNAME = new QName(
			"http://www.xml-cml.org/schema", "eigen");
	private final static QName _Label_QNAME = new QName(
			"http://www.xml-cml.org/schema", "label");
	private final static QName _Peak_QNAME = new QName(
			"http://www.xml-cml.org/schema", "peak");
	private final static QName _Length_QNAME = new QName(
			"http://www.xml-cml.org/schema", "length");
	private final static QName _ReactantList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "reactantList");
	private final static QName _Substance_QNAME = new QName(
			"http://www.xml-cml.org/schema", "substance");
	private final static QName _FragmentList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "fragmentList");
	private final static QName _Amount_QNAME = new QName(
			"http://www.xml-cml.org/schema", "amount");
	private final static QName _MetadataList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "metadataList");
	private final static QName _Dimension_QNAME = new QName(
			"http://www.xml-cml.org/schema", "dimension");
	private final static QName _Definition_QNAME = new QName(
			"http://www.xml-cml.org/schema", "definition");
	private final static QName _Parameter_QNAME = new QName(
			"http://www.xml-cml.org/schema", "parameter");
	private final static QName _IsotopeList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "isotopeList");
	private final static QName _Array_QNAME = new QName(
			"http://www.xml-cml.org/schema", "array");
	private final static QName _ReactionList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "reactionList");
	private final static QName _Xaxis_QNAME = new QName(
			"http://www.xml-cml.org/schema", "xaxis");
	private final static QName _Point3_QNAME = new QName(
			"http://www.xml-cml.org/schema", "point3");
	private final static QName _Description_QNAME = new QName(
			"http://www.xml-cml.org/schema", "description");
	private final static QName _Link_QNAME = new QName(
			"http://www.xml-cml.org/schema", "link");
	private final static QName _UnitList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "unitList");
	private final static QName _Abundance_QNAME = new QName(
			"http://www.xml-cml.org/schema", "abundance");
	private final static QName _AtomicBasisFunction_QNAME = new QName(
			"http://www.xml-cml.org/schema", "atomicBasisFunction");
	private final static QName _Region_QNAME = new QName(
			"http://www.xml-cml.org/schema", "region");
	private final static QName _BandList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "bandList");
	private final static QName _ParameterList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "parameterList");
	private final static QName _SpectrumData_QNAME = new QName(
			"http://www.xml-cml.org/schema", "spectrumData");
	private final static QName _Name_QNAME = new QName(
			"http://www.xml-cml.org/schema", "name");
	private final static QName _Torsion_QNAME = new QName(
			"http://www.xml-cml.org/schema", "torsion");
	private final static QName _PotentialList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "potentialList");
	private final static QName _Unit_QNAME = new QName(
			"http://www.xml-cml.org/schema", "unit");
	private final static QName _Entry_QNAME = new QName(
			"http://www.xml-cml.org/schema", "entry");
	private final static QName _KpointList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "kpointList");
	private final static QName _List_QNAME = new QName(
			"http://www.xml-cml.org/schema", "list");
	private final static QName _SpectrumList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "spectrumList");
	private final static QName _ActionList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "actionList");
	private final static QName _Potential_QNAME = new QName(
			"http://www.xml-cml.org/schema", "potential");
	private final static QName _Line3_QNAME = new QName(
			"http://www.xml-cml.org/schema", "line3");
	private final static QName _SpectatorList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "spectatorList");
	private final static QName _ArrayList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "arrayList");
	private final static QName _Symmetry_QNAME = new QName(
			"http://www.xml-cml.org/schema", "symmetry");
	private final static QName _ConditionList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "conditionList");
	private final static QName _AtomParity_QNAME = new QName(
			"http://www.xml-cml.org/schema", "atomParity");
	private final static QName _TableHeaderCell_QNAME = new QName(
			"http://www.xml-cml.org/schema", "tableHeaderCell");
	private final static QName _TableRow_QNAME = new QName(
			"http://www.xml-cml.org/schema", "tableRow");
	private final static QName _TransitionState_QNAME = new QName(
			"http://www.xml-cml.org/schema", "transitionState");
	private final static QName _PeakStructure_QNAME = new QName(
			"http://www.xml-cml.org/schema", "peakStructure");
	private final static QName _UnitTypeList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "unitTypeList");
	private final static QName _Atom_QNAME = new QName(
			"http://www.xml-cml.org/schema", "atom");
	private final static QName _AnyCml_QNAME = new QName(
			"http://www.xml-cml.org/schema", "anyCml");
	private final static QName _Spectator_QNAME = new QName(
			"http://www.xml-cml.org/schema", "spectator");
	private final static QName _ReactiveCentre_QNAME = new QName(
			"http://www.xml-cml.org/schema", "reactiveCentre");
	private final static QName _Sphere3_QNAME = new QName(
			"http://www.xml-cml.org/schema", "sphere3");
	private final static QName _Vector3_QNAME = new QName(
			"http://www.xml-cml.org/schema", "vector3");
	private final static QName _ZMatrix_QNAME = new QName(
			"http://www.xml-cml.org/schema", "zMatrix");
	private final static QName _PotentialForm_QNAME = new QName(
			"http://www.xml-cml.org/schema", "potentialForm");
	private final static QName _Sample_QNAME = new QName(
			"http://www.xml-cml.org/schema", "sample");
	private final static QName _Plane3_QNAME = new QName(
			"http://www.xml-cml.org/schema", "plane3");
	private final static QName _Gradient_QNAME = new QName(
			"http://www.xml-cml.org/schema", "gradient");
	private final static QName _BondArray_QNAME = new QName(
			"http://www.xml-cml.org/schema", "bondArray");
	private final static QName _Observation_QNAME = new QName(
			"http://www.xml-cml.org/schema", "observation");
	private final static QName _PropertyList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "propertyList");
	private final static QName _Reaction_QNAME = new QName(
			"http://www.xml-cml.org/schema", "reaction");
	private final static QName _Product_QNAME = new QName(
			"http://www.xml-cml.org/schema", "product");
	private final static QName _LatticeVector_QNAME = new QName(
			"http://www.xml-cml.org/schema", "latticeVector");
	private final static QName _Table_QNAME = new QName(
			"http://www.xml-cml.org/schema", "table");
	private final static QName _Map_QNAME = new QName(
			"http://www.xml-cml.org/schema", "map");
	private final static QName _Mechanism_QNAME = new QName(
			"http://www.xml-cml.org/schema", "mechanism");
	private final static QName _Particle_QNAME = new QName(
			"http://www.xml-cml.org/schema", "particle");
	private final static QName _Angle_QNAME = new QName(
			"http://www.xml-cml.org/schema", "angle");
	private final static QName _PeakGroup_QNAME = new QName(
			"http://www.xml-cml.org/schema", "peakGroup");
	private final static QName _BondSet_QNAME = new QName(
			"http://www.xml-cml.org/schema", "bondSet");
	private final static QName _SubstanceList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "substanceList");
	private final static QName _MoleculeList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "moleculeList");
	private final static QName _UnitType_QNAME = new QName(
			"http://www.xml-cml.org/schema", "unitType");
	private final static QName _CellParameter_QNAME = new QName(
			"http://www.xml-cml.org/schema", "cellParameter");
	private final static QName _Yaxis_QNAME = new QName(
			"http://www.xml-cml.org/schema", "yaxis");
	private final static QName _Matrix_QNAME = new QName(
			"http://www.xml-cml.org/schema", "matrix");
	private final static QName _Isotope_QNAME = new QName(
			"http://www.xml-cml.org/schema", "isotope");
	private final static QName _ReactionScheme_QNAME = new QName(
			"http://www.xml-cml.org/schema", "reactionScheme");
	private final static QName _Transform3_QNAME = new QName(
			"http://www.xml-cml.org/schema", "transform3");
	private final static QName _MechanismComponent_QNAME = new QName(
			"http://www.xml-cml.org/schema", "mechanismComponent");
	private final static QName _Crystal_QNAME = new QName(
			"http://www.xml-cml.org/schema", "crystal");
	private final static QName _Cml_QNAME = new QName(
			"http://www.xml-cml.org/schema", "cml");
	private final static QName _Reactant_QNAME = new QName(
			"http://www.xml-cml.org/schema", "reactant");
	private final static QName _Stmml_QNAME = new QName(
			"http://www.xml-cml.org/schema", "stmml");
	private final static QName _Object_QNAME = new QName(
			"http://www.xml-cml.org/schema", "object");
	private final static QName _ProductList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "productList");
	private final static QName _Molecule_QNAME = new QName(
			"http://www.xml-cml.org/schema", "molecule");
	private final static QName _TableRowList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "tableRowList");
	private final static QName _BondStereo_QNAME = new QName(
			"http://www.xml-cml.org/schema", "bondStereo");
	private final static QName _Spectrum_QNAME = new QName(
			"http://www.xml-cml.org/schema", "spectrum");
	private final static QName _Dictionary_QNAME = new QName(
			"http://www.xml-cml.org/schema", "dictionary");
	private final static QName _System_QNAME = new QName(
			"http://www.xml-cml.org/schema", "system");
	private final static QName _Scalar_QNAME = new QName(
			"http://www.xml-cml.org/schema", "scalar");
	private final static QName _AtomSet_QNAME = new QName(
			"http://www.xml-cml.org/schema", "atomSet");
	private final static QName _Documentation_QNAME = new QName(
			"http://www.xml-cml.org/schema", "documentation");
	private final static QName _Module_QNAME = new QName(
			"http://www.xml-cml.org/schema", "module");
	private final static QName _ReactionStep_QNAME = new QName(
			"http://www.xml-cml.org/schema", "reactionStep");
	private final static QName _TableContent_QNAME = new QName(
			"http://www.xml-cml.org/schema", "tableContent");
	private final static QName _Identifier_QNAME = new QName(
			"http://www.xml-cml.org/schema", "identifier");
	private final static QName _TableCell_QNAME = new QName(
			"http://www.xml-cml.org/schema", "tableCell");
	private final static QName _BondTypeList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "bondTypeList");
	private final static QName _AtomType_QNAME = new QName(
			"http://www.xml-cml.org/schema", "atomType");
	private final static QName _AtomArray_QNAME = new QName(
			"http://www.xml-cml.org/schema", "atomArray");
	private final static QName _AtomTypeList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "atomTypeList");
	private final static QName _Band_QNAME = new QName(
			"http://www.xml-cml.org/schema", "band");
	private final static QName _Join_QNAME = new QName(
			"http://www.xml-cml.org/schema", "join");
	private final static QName _Action_QNAME = new QName(
			"http://www.xml-cml.org/schema", "action");
	private final static QName _Electron_QNAME = new QName(
			"http://www.xml-cml.org/schema", "electron");
	private final static QName _Property_QNAME = new QName(
			"http://www.xml-cml.org/schema", "property");
	private final static QName _ReactionStepList_QNAME = new QName(
			"http://www.xml-cml.org/schema", "reactionStepList");
	private final static QName _Metadata_QNAME = new QName(
			"http://www.xml-cml.org/schema", "metadata");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: org.xml_cml.schema
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Metadata }
	 * 
	 */
	public Metadata createMetadata() {
		return new Metadata();
	}

	/**
	 * Create an instance of {@link ReactionStepList }
	 * 
	 */
	public ReactionStepList createReactionStepList() {
		return new ReactionStepList();
	}

	/**
	 * Create an instance of {@link Electron }
	 * 
	 */
	public Electron createElectron() {
		return new Electron();
	}

	/**
	 * Create an instance of {@link Property }
	 * 
	 */
	public Property createProperty() {
		return new Property();
	}

	/**
	 * Create an instance of {@link Action }
	 * 
	 */
	public Action createAction() {
		return new Action();
	}

	/**
	 * Create an instance of {@link AtomArray }
	 * 
	 */
	public AtomArray createAtomArray() {
		return new AtomArray();
	}

	/**
	 * Create an instance of {@link AtomTypeList }
	 * 
	 */
	public AtomTypeList createAtomTypeList() {
		return new AtomTypeList();
	}

	/**
	 * Create an instance of {@link Band }
	 * 
	 */
	public Band createBand() {
		return new Band();
	}

	/**
	 * Create an instance of {@link Join }
	 * 
	 */
	public Join createJoin() {
		return new Join();
	}

	/**
	 * Create an instance of {@link AtomType }
	 * 
	 */
	public AtomType createAtomType() {
		return new AtomType();
	}

	/**
	 * Create an instance of {@link BondTypeList }
	 * 
	 */
	public BondTypeList createBondTypeList() {
		return new BondTypeList();
	}

	/**
	 * Create an instance of {@link Identifier }
	 * 
	 */
	public Identifier createIdentifier() {
		return new Identifier();
	}

	/**
	 * Create an instance of {@link TableCell }
	 * 
	 */
	public TableCell createTableCell() {
		return new TableCell();
	}

	/**
	 * Create an instance of {@link ReactionStep }
	 * 
	 */
	public ReactionStep createReactionStep() {
		return new ReactionStep();
	}

	/**
	 * Create an instance of {@link TableContent }
	 * 
	 */
	public TableContent createTableContent() {
		return new TableContent();
	}

	/**
	 * Create an instance of {@link Documentation }
	 * 
	 */
	public Documentation createDocumentation() {
		return new Documentation();
	}

	/**
	 * Create an instance of {@link Module }
	 * 
	 */
	public Module createModule() {
		return new Module();
	}

	/**
	 * Create an instance of {@link AtomSet }
	 * 
	 */
	public AtomSet createAtomSet() {
		return new AtomSet();
	}

	/**
	 * Create an instance of {@link Scalar }
	 * 
	 */
	public Scalar createScalar() {
		return new Scalar();
	}

	/**
	 * Create an instance of {@link Dictionary }
	 * 
	 */
	public Dictionary createDictionary() {
		return new Dictionary();
	}

	/**
	 * Create an instance of {@link System }
	 * 
	 */
	public System createSystem() {
		return new System();
	}

	/**
	 * Create an instance of {@link BondStereo }
	 * 
	 */
	public BondStereo createBondStereo() {
		return new BondStereo();
	}

	/**
	 * Create an instance of {@link Spectrum }
	 * 
	 */
	public Spectrum createSpectrum() {
		return new Spectrum();
	}

	/**
	 * Create an instance of {@link TableRowList }
	 * 
	 */
	public TableRowList createTableRowList() {
		return new TableRowList();
	}

	/**
	 * Create an instance of {@link Molecule }
	 * 
	 */
	public Molecule createMolecule() {
		return new Molecule();
	}

	/**
	 * Create an instance of {@link ProductList }
	 * 
	 */
	public ProductList createProductList() {
		return new ProductList();
	}

	/**
	 * Create an instance of {@link org.xml_cml.schema.Object }
	 * 
	 */
	public org.xml_cml.schema.Object createObject() {
		return new org.xml_cml.schema.Object();
	}

	/**
	 * Create an instance of {@link Stmml }
	 * 
	 */
	public Stmml createStmml() {
		return new Stmml();
	}

	/**
	 * Create an instance of {@link Reactant }
	 * 
	 */
	public Reactant createReactant() {
		return new Reactant();
	}

	/**
	 * Create an instance of {@link Cml }
	 * 
	 */
	public Cml createCml() {
		return new Cml();
	}

	/**
	 * Create an instance of {@link Crystal }
	 * 
	 */
	public Crystal createCrystal() {
		return new Crystal();
	}

	/**
	 * Create an instance of {@link MechanismComponent }
	 * 
	 */
	public MechanismComponent createMechanismComponent() {
		return new MechanismComponent();
	}

	/**
	 * Create an instance of {@link Transform3 }
	 * 
	 */
	public Transform3 createTransform3() {
		return new Transform3();
	}

	/**
	 * Create an instance of {@link ReactionScheme }
	 * 
	 */
	public ReactionScheme createReactionScheme() {
		return new ReactionScheme();
	}

	/**
	 * Create an instance of {@link Isotope }
	 * 
	 */
	public Isotope createIsotope() {
		return new Isotope();
	}

	/**
	 * Create an instance of {@link Matrix }
	 * 
	 */
	public Matrix createMatrix() {
		return new Matrix();
	}

	/**
	 * Create an instance of {@link Yaxis }
	 * 
	 */
	public Yaxis createYaxis() {
		return new Yaxis();
	}

	/**
	 * Create an instance of {@link CellParameter }
	 * 
	 */
	public CellParameter createCellParameter() {
		return new CellParameter();
	}

	/**
	 * Create an instance of {@link MoleculeList }
	 * 
	 */
	public MoleculeList createMoleculeList() {
		return new MoleculeList();
	}

	/**
	 * Create an instance of {@link UnitType }
	 * 
	 */
	public UnitType createUnitType() {
		return new UnitType();
	}

	/**
	 * Create an instance of {@link SubstanceList }
	 * 
	 */
	public SubstanceList createSubstanceList() {
		return new SubstanceList();
	}

	/**
	 * Create an instance of {@link BondSet }
	 * 
	 */
	public BondSet createBondSet() {
		return new BondSet();
	}

	/**
	 * Create an instance of {@link PeakGroup }
	 * 
	 */
	public PeakGroup createPeakGroup() {
		return new PeakGroup();
	}

	/**
	 * Create an instance of {@link Angle }
	 * 
	 */
	public Angle createAngle() {
		return new Angle();
	}

	/**
	 * Create an instance of {@link Particle }
	 * 
	 */
	public Particle createParticle() {
		return new Particle();
	}

	/**
	 * Create an instance of {@link Mechanism }
	 * 
	 */
	public Mechanism createMechanism() {
		return new Mechanism();
	}

	/**
	 * Create an instance of {@link Map }
	 * 
	 */
	public Map createMap() {
		return new Map();
	}

	/**
	 * Create an instance of {@link Table }
	 * 
	 */
	public Table createTable() {
		return new Table();
	}

	/**
	 * Create an instance of {@link LatticeVector }
	 * 
	 */
	public LatticeVector createLatticeVector() {
		return new LatticeVector();
	}

	/**
	 * Create an instance of {@link Product }
	 * 
	 */
	public Product createProduct() {
		return new Product();
	}

	/**
	 * Create an instance of {@link Reaction }
	 * 
	 */
	public Reaction createReaction() {
		return new Reaction();
	}

	/**
	 * Create an instance of {@link BondArray }
	 * 
	 */
	public BondArray createBondArray() {
		return new BondArray();
	}

	/**
	 * Create an instance of {@link Observation }
	 * 
	 */
	public Observation createObservation() {
		return new Observation();
	}

	/**
	 * Create an instance of {@link PropertyList }
	 * 
	 */
	public PropertyList createPropertyList() {
		return new PropertyList();
	}

	/**
	 * Create an instance of {@link Gradient }
	 * 
	 */
	public Gradient createGradient() {
		return new Gradient();
	}

	/**
	 * Create an instance of {@link Plane3 }
	 * 
	 */
	public Plane3 createPlane3() {
		return new Plane3();
	}

	/**
	 * Create an instance of {@link Sample }
	 * 
	 */
	public Sample createSample() {
		return new Sample();
	}

	/**
	 * Create an instance of {@link PotentialForm }
	 * 
	 */
	public PotentialForm createPotentialForm() {
		return new PotentialForm();
	}

	/**
	 * Create an instance of {@link ZMatrix }
	 * 
	 */
	public ZMatrix createZMatrix() {
		return new ZMatrix();
	}

	/**
	 * Create an instance of {@link ReactiveCentre }
	 * 
	 */
	public ReactiveCentre createReactiveCentre() {
		return new ReactiveCentre();
	}

	/**
	 * Create an instance of {@link Sphere3 }
	 * 
	 */
	public Sphere3 createSphere3() {
		return new Sphere3();
	}

	/**
	 * Create an instance of {@link Vector3 }
	 * 
	 */
	public Vector3 createVector3() {
		return new Vector3();
	}

	/**
	 * Create an instance of {@link Spectator }
	 * 
	 */
	public Spectator createSpectator() {
		return new Spectator();
	}

	/**
	 * Create an instance of {@link Atom }
	 * 
	 */
	public Atom createAtom() {
		return new Atom();
	}

	/**
	 * Create an instance of {@link UnitTypeList }
	 * 
	 */
	public UnitTypeList createUnitTypeList() {
		return new UnitTypeList();
	}

	/**
	 * Create an instance of {@link PeakStructure }
	 * 
	 */
	public PeakStructure createPeakStructure() {
		return new PeakStructure();
	}

	/**
	 * Create an instance of {@link TransitionState }
	 * 
	 */
	public TransitionState createTransitionState() {
		return new TransitionState();
	}

	/**
	 * Create an instance of {@link TableRow }
	 * 
	 */
	public TableRow createTableRow() {
		return new TableRow();
	}

	/**
	 * Create an instance of {@link TableHeaderCell }
	 * 
	 */
	public TableHeaderCell createTableHeaderCell() {
		return new TableHeaderCell();
	}

	/**
	 * Create an instance of {@link AtomParity }
	 * 
	 */
	public AtomParity createAtomParity() {
		return new AtomParity();
	}

	/**
	 * Create an instance of {@link ConditionList }
	 * 
	 */
	public ConditionList createConditionList() {
		return new ConditionList();
	}

	/**
	 * Create an instance of {@link Symmetry }
	 * 
	 */
	public Symmetry createSymmetry() {
		return new Symmetry();
	}

	/**
	 * Create an instance of {@link ArrayList }
	 * 
	 */
	public ArrayList createArrayList() {
		return new ArrayList();
	}

	/**
	 * Create an instance of {@link Line3 }
	 * 
	 */
	public Line3 createLine3() {
		return new Line3();
	}

	/**
	 * Create an instance of {@link SpectatorList }
	 * 
	 */
	public SpectatorList createSpectatorList() {
		return new SpectatorList();
	}

	/**
	 * Create an instance of {@link Potential }
	 * 
	 */
	public Potential createPotential() {
		return new Potential();
	}

	/**
	 * Create an instance of {@link ActionList }
	 * 
	 */
	public ActionList createActionList() {
		return new ActionList();
	}

	/**
	 * Create an instance of {@link SpectrumList }
	 * 
	 */
	public SpectrumList createSpectrumList() {
		return new SpectrumList();
	}

	/**
	 * Create an instance of {@link KpointList }
	 * 
	 */
	public KpointList createKpointList() {
		return new KpointList();
	}

	/**
	 * Create an instance of {@link List }
	 * 
	 */
	public List createList() {
		return new List();
	}

	/**
	 * Create an instance of {@link Entry }
	 * 
	 */
	public Entry createEntry() {
		return new Entry();
	}

	/**
	 * Create an instance of {@link PotentialList }
	 * 
	 */
	public PotentialList createPotentialList() {
		return new PotentialList();
	}

	/**
	 * Create an instance of {@link Unit }
	 * 
	 */
	public Unit createUnit() {
		return new Unit();
	}

	/**
	 * Create an instance of {@link Torsion }
	 * 
	 */
	public Torsion createTorsion() {
		return new Torsion();
	}

	/**
	 * Create an instance of {@link Name }
	 * 
	 */
	public Name createName() {
		return new Name();
	}

	/**
	 * Create an instance of {@link BandList }
	 * 
	 */
	public BandList createBandList() {
		return new BandList();
	}

	/**
	 * Create an instance of {@link ParameterList }
	 * 
	 */
	public ParameterList createParameterList() {
		return new ParameterList();
	}

	/**
	 * Create an instance of {@link SpectrumData }
	 * 
	 */
	public SpectrumData createSpectrumData() {
		return new SpectrumData();
	}

	/**
	 * Create an instance of {@link Region }
	 * 
	 */
	public Region createRegion() {
		return new Region();
	}

	/**
	 * Create an instance of {@link AtomicBasisFunction }
	 * 
	 */
	public AtomicBasisFunction createAtomicBasisFunction() {
		return new AtomicBasisFunction();
	}

	/**
	 * Create an instance of {@link Abundance }
	 * 
	 */
	public Abundance createAbundance() {
		return new Abundance();
	}

	/**
	 * Create an instance of {@link Link }
	 * 
	 */
	public Link createLink() {
		return new Link();
	}

	/**
	 * Create an instance of {@link UnitList }
	 * 
	 */
	public UnitList createUnitList() {
		return new UnitList();
	}

	/**
	 * Create an instance of {@link Description }
	 * 
	 */
	public Description createDescription() {
		return new Description();
	}

	/**
	 * Create an instance of {@link Point3 }
	 * 
	 */
	public Point3 createPoint3() {
		return new Point3();
	}

	/**
	 * Create an instance of {@link Xaxis }
	 * 
	 */
	public Xaxis createXaxis() {
		return new Xaxis();
	}

	/**
	 * Create an instance of {@link ReactionList }
	 * 
	 */
	public ReactionList createReactionList() {
		return new ReactionList();
	}

	/**
	 * Create an instance of {@link Array }
	 * 
	 */
	public Array createArray() {
		return new Array();
	}

	/**
	 * Create an instance of {@link IsotopeList }
	 * 
	 */
	public IsotopeList createIsotopeList() {
		return new IsotopeList();
	}

	/**
	 * Create an instance of {@link Parameter }
	 * 
	 */
	public Parameter createParameter() {
		return new Parameter();
	}

	/**
	 * Create an instance of {@link Definition }
	 * 
	 */
	public Definition createDefinition() {
		return new Definition();
	}

	/**
	 * Create an instance of {@link Dimension }
	 * 
	 */
	public Dimension createDimension() {
		return new Dimension();
	}

	/**
	 * Create an instance of {@link MetadataList }
	 * 
	 */
	public MetadataList createMetadataList() {
		return new MetadataList();
	}

	/**
	 * Create an instance of {@link Amount }
	 * 
	 */
	public Amount createAmount() {
		return new Amount();
	}

	/**
	 * Create an instance of {@link FragmentList }
	 * 
	 */
	public FragmentList createFragmentList() {
		return new FragmentList();
	}

	/**
	 * Create an instance of {@link ReactantList }
	 * 
	 */
	public ReactantList createReactantList() {
		return new ReactantList();
	}

	/**
	 * Create an instance of {@link Substance }
	 * 
	 */
	public Substance createSubstance() {
		return new Substance();
	}

	/**
	 * Create an instance of {@link Length }
	 * 
	 */
	public Length createLength() {
		return new Length();
	}

	/**
	 * Create an instance of {@link Label }
	 * 
	 */
	public Label createLabel() {
		return new Label();
	}

	/**
	 * Create an instance of {@link Peak }
	 * 
	 */
	public Peak createPeak() {
		return new Peak();
	}

	/**
	 * Create an instance of {@link Eigen }
	 * 
	 */
	public Eigen createEigen() {
		return new Eigen();
	}

	/**
	 * Create an instance of {@link Bond }
	 * 
	 */
	public Bond createBond() {
		return new Bond();
	}

	/**
	 * Create an instance of {@link BasisSet }
	 * 
	 */
	public BasisSet createBasisSet() {
		return new BasisSet();
	}

	/**
	 * Create an instance of {@link TableHeader }
	 * 
	 */
	public TableHeader createTableHeader() {
		return new TableHeader();
	}

	/**
	 * Create an instance of {@link Kpoint }
	 * 
	 */
	public Kpoint createKpoint() {
		return new Kpoint();
	}

	/**
	 * Create an instance of {@link Fragment }
	 * 
	 */
	public Fragment createFragment() {
		return new Fragment();
	}

	/**
	 * Create an instance of {@link Lattice }
	 * 
	 */
	public Lattice createLattice() {
		return new Lattice();
	}

	/**
	 * Create an instance of {@link BondType }
	 * 
	 */
	public BondType createBondType() {
		return new BondType();
	}

	/**
	 * Create an instance of {@link Formula }
	 * 
	 */
	public Formula createFormula() {
		return new Formula();
	}

	/**
	 * Create an instance of {@link PeakList }
	 * 
	 */
	public PeakList createPeakList() {
		return new PeakList();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link PeakList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "peakList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<PeakList> createPeakList(PeakList value) {
		return new JAXBElement<PeakList>(_PeakList_QNAME, PeakList.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Formula }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "formula", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Formula> createFormula(Formula value) {
		return new JAXBElement<Formula>(_Formula_QNAME, Formula.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BondType }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "bondType", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<BondType> createBondType(BondType value) {
		return new JAXBElement<BondType>(_BondType_QNAME, BondType.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Lattice }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "lattice", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Lattice> createLattice(Lattice value) {
		return new JAXBElement<Lattice>(_Lattice_QNAME, Lattice.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Fragment }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "fragment", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Fragment> createFragment(Fragment value) {
		return new JAXBElement<Fragment>(_Fragment_QNAME, Fragment.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Kpoint }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "kpoint", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Kpoint> createKpoint(Kpoint value) {
		return new JAXBElement<Kpoint>(_Kpoint_QNAME, Kpoint.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BasisSet }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "basisSet", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<BasisSet> createBasisSet(BasisSet value) {
		return new JAXBElement<BasisSet>(_BasisSet_QNAME, BasisSet.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link TableHeader }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "tableHeader", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<TableHeader> createTableHeader(TableHeader value) {
		return new JAXBElement<TableHeader>(_TableHeader_QNAME,
				TableHeader.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Bond }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "bond", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Bond> createBond(Bond value) {
		return new JAXBElement<Bond>(_Bond_QNAME, Bond.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Eigen }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "eigen", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Eigen> createEigen(Eigen value) {
		return new JAXBElement<Eigen>(_Eigen_QNAME, Eigen.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Label }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "label", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Label> createLabel(Label value) {
		return new JAXBElement<Label>(_Label_QNAME, Label.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Peak }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "peak", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Peak> createPeak(Peak value) {
		return new JAXBElement<Peak>(_Peak_QNAME, Peak.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Length }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "length", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Length> createLength(Length value) {
		return new JAXBElement<Length>(_Length_QNAME, Length.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ReactantList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "reactantList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ReactantList> createReactantList(ReactantList value) {
		return new JAXBElement<ReactantList>(_ReactantList_QNAME,
				ReactantList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Substance }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "substance", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Substance> createSubstance(Substance value) {
		return new JAXBElement<Substance>(_Substance_QNAME, Substance.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link FragmentList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "fragmentList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<FragmentList> createFragmentList(FragmentList value) {
		return new JAXBElement<FragmentList>(_FragmentList_QNAME,
				FragmentList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Amount }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "amount", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Amount> createAmount(Amount value) {
		return new JAXBElement<Amount>(_Amount_QNAME, Amount.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link MetadataList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "metadataList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<MetadataList> createMetadataList(MetadataList value) {
		return new JAXBElement<MetadataList>(_MetadataList_QNAME,
				MetadataList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Dimension }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "dimension", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Dimension> createDimension(Dimension value) {
		return new JAXBElement<Dimension>(_Dimension_QNAME, Dimension.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Definition }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "definition", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Definition> createDefinition(Definition value) {
		return new JAXBElement<Definition>(_Definition_QNAME, Definition.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Parameter }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "parameter", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Parameter> createParameter(Parameter value) {
		return new JAXBElement<Parameter>(_Parameter_QNAME, Parameter.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link IsotopeList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "isotopeList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<IsotopeList> createIsotopeList(IsotopeList value) {
		return new JAXBElement<IsotopeList>(_IsotopeList_QNAME,
				IsotopeList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Array }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "array", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Array> createArray(Array value) {
		return new JAXBElement<Array>(_Array_QNAME, Array.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ReactionList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "reactionList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ReactionList> createReactionList(ReactionList value) {
		return new JAXBElement<ReactionList>(_ReactionList_QNAME,
				ReactionList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Xaxis }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "xaxis", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Xaxis> createXaxis(Xaxis value) {
		return new JAXBElement<Xaxis>(_Xaxis_QNAME, Xaxis.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Point3 }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "point3", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Point3> createPoint3(Point3 value) {
		return new JAXBElement<Point3>(_Point3_QNAME, Point3.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Description }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "description", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Description> createDescription(Description value) {
		return new JAXBElement<Description>(_Description_QNAME,
				Description.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Link }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "link", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Link> createLink(Link value) {
		return new JAXBElement<Link>(_Link_QNAME, Link.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UnitList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "unitList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<UnitList> createUnitList(UnitList value) {
		return new JAXBElement<UnitList>(_UnitList_QNAME, UnitList.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Abundance }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "abundance", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Abundance> createAbundance(Abundance value) {
		return new JAXBElement<Abundance>(_Abundance_QNAME, Abundance.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link AtomicBasisFunction }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "atomicBasisFunction", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<AtomicBasisFunction> createAtomicBasisFunction(
			AtomicBasisFunction value) {
		return new JAXBElement<AtomicBasisFunction>(_AtomicBasisFunction_QNAME,
				AtomicBasisFunction.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Region }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "region", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Region> createRegion(Region value) {
		return new JAXBElement<Region>(_Region_QNAME, Region.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BandList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "bandList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<BandList> createBandList(BandList value) {
		return new JAXBElement<BandList>(_BandList_QNAME, BandList.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ParameterList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "parameterList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ParameterList> createParameterList(ParameterList value) {
		return new JAXBElement<ParameterList>(_ParameterList_QNAME,
				ParameterList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link SpectrumData }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "spectrumData", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<SpectrumData> createSpectrumData(SpectrumData value) {
		return new JAXBElement<SpectrumData>(_SpectrumData_QNAME,
				SpectrumData.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Name }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "name", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Name> createName(Name value) {
		return new JAXBElement<Name>(_Name_QNAME, Name.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Torsion }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "torsion", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Torsion> createTorsion(Torsion value) {
		return new JAXBElement<Torsion>(_Torsion_QNAME, Torsion.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link PotentialList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "potentialList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<PotentialList> createPotentialList(PotentialList value) {
		return new JAXBElement<PotentialList>(_PotentialList_QNAME,
				PotentialList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Unit }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "unit", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Unit> createUnit(Unit value) {
		return new JAXBElement<Unit>(_Unit_QNAME, Unit.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Entry }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "entry", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Entry> createEntry(Entry value) {
		return new JAXBElement<Entry>(_Entry_QNAME, Entry.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link KpointList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "kpointList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<KpointList> createKpointList(KpointList value) {
		return new JAXBElement<KpointList>(_KpointList_QNAME, KpointList.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "list", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<List> createList(List value) {
		return new JAXBElement<List>(_List_QNAME, List.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link SpectrumList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "spectrumList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<SpectrumList> createSpectrumList(SpectrumList value) {
		return new JAXBElement<SpectrumList>(_SpectrumList_QNAME,
				SpectrumList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ActionList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "actionList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ActionList> createActionList(ActionList value) {
		return new JAXBElement<ActionList>(_ActionList_QNAME, ActionList.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Potential }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "potential", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Potential> createPotential(Potential value) {
		return new JAXBElement<Potential>(_Potential_QNAME, Potential.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Line3 }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "line3", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Line3> createLine3(Line3 value) {
		return new JAXBElement<Line3>(_Line3_QNAME, Line3.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link SpectatorList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "spectatorList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<SpectatorList> createSpectatorList(SpectatorList value) {
		return new JAXBElement<SpectatorList>(_SpectatorList_QNAME,
				SpectatorList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ArrayList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "arrayList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ArrayList> createArrayList(ArrayList value) {
		return new JAXBElement<ArrayList>(_ArrayList_QNAME, ArrayList.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Symmetry }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "symmetry", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Symmetry> createSymmetry(Symmetry value) {
		return new JAXBElement<Symmetry>(_Symmetry_QNAME, Symmetry.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ConditionList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "conditionList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ConditionList> createConditionList(ConditionList value) {
		return new JAXBElement<ConditionList>(_ConditionList_QNAME,
				ConditionList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link AtomParity }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "atomParity", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<AtomParity> createAtomParity(AtomParity value) {
		return new JAXBElement<AtomParity>(_AtomParity_QNAME, AtomParity.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link TableHeaderCell }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "tableHeaderCell", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<TableHeaderCell> createTableHeaderCell(
			TableHeaderCell value) {
		return new JAXBElement<TableHeaderCell>(_TableHeaderCell_QNAME,
				TableHeaderCell.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link TableRow }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "tableRow", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<TableRow> createTableRow(TableRow value) {
		return new JAXBElement<TableRow>(_TableRow_QNAME, TableRow.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link TransitionState }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "transitionState", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<TransitionState> createTransitionState(
			TransitionState value) {
		return new JAXBElement<TransitionState>(_TransitionState_QNAME,
				TransitionState.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link PeakStructure }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "peakStructure", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<PeakStructure> createPeakStructure(PeakStructure value) {
		return new JAXBElement<PeakStructure>(_PeakStructure_QNAME,
				PeakStructure.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UnitTypeList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "unitTypeList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<UnitTypeList> createUnitTypeList(UnitTypeList value) {
		return new JAXBElement<UnitTypeList>(_UnitTypeList_QNAME,
				UnitTypeList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Atom }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "atom", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Atom> createAtom(Atom value) {
		return new JAXBElement<Atom>(_Atom_QNAME, Atom.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link java.lang.Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "anyCml")
	public JAXBElement<java.lang.Object> createAnyCml(java.lang.Object value) {
		return new JAXBElement<java.lang.Object>(_AnyCml_QNAME,
				java.lang.Object.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Spectator }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "spectator", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Spectator> createSpectator(Spectator value) {
		return new JAXBElement<Spectator>(_Spectator_QNAME, Spectator.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ReactiveCentre }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "reactiveCentre", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ReactiveCentre> createReactiveCentre(ReactiveCentre value) {
		return new JAXBElement<ReactiveCentre>(_ReactiveCentre_QNAME,
				ReactiveCentre.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Sphere3 }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "sphere3", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Sphere3> createSphere3(Sphere3 value) {
		return new JAXBElement<Sphere3>(_Sphere3_QNAME, Sphere3.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Vector3 }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "vector3", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Vector3> createVector3(Vector3 value) {
		return new JAXBElement<Vector3>(_Vector3_QNAME, Vector3.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ZMatrix }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "zMatrix", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ZMatrix> createZMatrix(ZMatrix value) {
		return new JAXBElement<ZMatrix>(_ZMatrix_QNAME, ZMatrix.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link PotentialForm }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "potentialForm", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<PotentialForm> createPotentialForm(PotentialForm value) {
		return new JAXBElement<PotentialForm>(_PotentialForm_QNAME,
				PotentialForm.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Sample }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "sample", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Sample> createSample(Sample value) {
		return new JAXBElement<Sample>(_Sample_QNAME, Sample.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Plane3 }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "plane3", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Plane3> createPlane3(Plane3 value) {
		return new JAXBElement<Plane3>(_Plane3_QNAME, Plane3.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Gradient }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "gradient", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Gradient> createGradient(Gradient value) {
		return new JAXBElement<Gradient>(_Gradient_QNAME, Gradient.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BondArray }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "bondArray", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<BondArray> createBondArray(BondArray value) {
		return new JAXBElement<BondArray>(_BondArray_QNAME, BondArray.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Observation }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "observation", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Observation> createObservation(Observation value) {
		return new JAXBElement<Observation>(_Observation_QNAME,
				Observation.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link PropertyList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "propertyList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<PropertyList> createPropertyList(PropertyList value) {
		return new JAXBElement<PropertyList>(_PropertyList_QNAME,
				PropertyList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Reaction }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "reaction", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Reaction> createReaction(Reaction value) {
		return new JAXBElement<Reaction>(_Reaction_QNAME, Reaction.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Product }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "product", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Product> createProduct(Product value) {
		return new JAXBElement<Product>(_Product_QNAME, Product.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link LatticeVector }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "latticeVector", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<LatticeVector> createLatticeVector(LatticeVector value) {
		return new JAXBElement<LatticeVector>(_LatticeVector_QNAME,
				LatticeVector.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Table }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "table", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Table> createTable(Table value) {
		return new JAXBElement<Table>(_Table_QNAME, Table.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Map }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "map", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Map> createMap(Map value) {
		return new JAXBElement<Map>(_Map_QNAME, Map.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Mechanism }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "mechanism", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Mechanism> createMechanism(Mechanism value) {
		return new JAXBElement<Mechanism>(_Mechanism_QNAME, Mechanism.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Particle }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "particle", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Particle> createParticle(Particle value) {
		return new JAXBElement<Particle>(_Particle_QNAME, Particle.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Angle }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "angle", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Angle> createAngle(Angle value) {
		return new JAXBElement<Angle>(_Angle_QNAME, Angle.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link PeakGroup }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "peakGroup", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<PeakGroup> createPeakGroup(PeakGroup value) {
		return new JAXBElement<PeakGroup>(_PeakGroup_QNAME, PeakGroup.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BondSet }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "bondSet", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<BondSet> createBondSet(BondSet value) {
		return new JAXBElement<BondSet>(_BondSet_QNAME, BondSet.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link SubstanceList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "substanceList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<SubstanceList> createSubstanceList(SubstanceList value) {
		return new JAXBElement<SubstanceList>(_SubstanceList_QNAME,
				SubstanceList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link MoleculeList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "moleculeList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<MoleculeList> createMoleculeList(MoleculeList value) {
		return new JAXBElement<MoleculeList>(_MoleculeList_QNAME,
				MoleculeList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UnitType }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "unitType", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<UnitType> createUnitType(UnitType value) {
		return new JAXBElement<UnitType>(_UnitType_QNAME, UnitType.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CellParameter }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "cellParameter", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<CellParameter> createCellParameter(CellParameter value) {
		return new JAXBElement<CellParameter>(_CellParameter_QNAME,
				CellParameter.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Yaxis }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "yaxis", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Yaxis> createYaxis(Yaxis value) {
		return new JAXBElement<Yaxis>(_Yaxis_QNAME, Yaxis.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Matrix }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "matrix", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Matrix> createMatrix(Matrix value) {
		return new JAXBElement<Matrix>(_Matrix_QNAME, Matrix.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Isotope }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "isotope", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Isotope> createIsotope(Isotope value) {
		return new JAXBElement<Isotope>(_Isotope_QNAME, Isotope.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ReactionScheme }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "reactionScheme", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ReactionScheme> createReactionScheme(ReactionScheme value) {
		return new JAXBElement<ReactionScheme>(_ReactionScheme_QNAME,
				ReactionScheme.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Transform3 }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "transform3", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Transform3> createTransform3(Transform3 value) {
		return new JAXBElement<Transform3>(_Transform3_QNAME, Transform3.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link MechanismComponent }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "mechanismComponent", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<MechanismComponent> createMechanismComponent(
			MechanismComponent value) {
		return new JAXBElement<MechanismComponent>(_MechanismComponent_QNAME,
				MechanismComponent.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Crystal }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "crystal", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Crystal> createCrystal(Crystal value) {
		return new JAXBElement<Crystal>(_Crystal_QNAME, Crystal.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Cml }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "cml", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Cml> createCml(Cml value) {
		return new JAXBElement<Cml>(_Cml_QNAME, Cml.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Reactant }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "reactant", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Reactant> createReactant(Reactant value) {
		return new JAXBElement<Reactant>(_Reactant_QNAME, Reactant.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Stmml }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "stmml", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Stmml> createStmml(Stmml value) {
		return new JAXBElement<Stmml>(_Stmml_QNAME, Stmml.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link org.xml_cml.schema.Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "object", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<org.xml_cml.schema.Object> createObject(
			org.xml_cml.schema.Object value) {
		return new JAXBElement<org.xml_cml.schema.Object>(_Object_QNAME,
				org.xml_cml.schema.Object.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ProductList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "productList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ProductList> createProductList(ProductList value) {
		return new JAXBElement<ProductList>(_ProductList_QNAME,
				ProductList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Molecule }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "molecule", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Molecule> createMolecule(Molecule value) {
		return new JAXBElement<Molecule>(_Molecule_QNAME, Molecule.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link TableRowList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "tableRowList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<TableRowList> createTableRowList(TableRowList value) {
		return new JAXBElement<TableRowList>(_TableRowList_QNAME,
				TableRowList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BondStereo }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "bondStereo", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<BondStereo> createBondStereo(BondStereo value) {
		return new JAXBElement<BondStereo>(_BondStereo_QNAME, BondStereo.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Spectrum }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "spectrum", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Spectrum> createSpectrum(Spectrum value) {
		return new JAXBElement<Spectrum>(_Spectrum_QNAME, Spectrum.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Dictionary }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "dictionary", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Dictionary> createDictionary(Dictionary value) {
		return new JAXBElement<Dictionary>(_Dictionary_QNAME, Dictionary.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link System }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "system", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<System> createSystem(System value) {
		return new JAXBElement<System>(_System_QNAME, System.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Scalar }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "scalar", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Scalar> createScalar(Scalar value) {
		return new JAXBElement<Scalar>(_Scalar_QNAME, Scalar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link AtomSet }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "atomSet", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<AtomSet> createAtomSet(AtomSet value) {
		return new JAXBElement<AtomSet>(_AtomSet_QNAME, AtomSet.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Documentation }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "documentation", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Documentation> createDocumentation(Documentation value) {
		return new JAXBElement<Documentation>(_Documentation_QNAME,
				Documentation.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Module }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "module", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Module> createModule(Module value) {
		return new JAXBElement<Module>(_Module_QNAME, Module.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ReactionStep }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "reactionStep", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ReactionStep> createReactionStep(ReactionStep value) {
		return new JAXBElement<ReactionStep>(_ReactionStep_QNAME,
				ReactionStep.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link TableContent }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "tableContent", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<TableContent> createTableContent(TableContent value) {
		return new JAXBElement<TableContent>(_TableContent_QNAME,
				TableContent.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Identifier }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "identifier", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Identifier> createIdentifier(Identifier value) {
		return new JAXBElement<Identifier>(_Identifier_QNAME, Identifier.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link TableCell }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "tableCell", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<TableCell> createTableCell(TableCell value) {
		return new JAXBElement<TableCell>(_TableCell_QNAME, TableCell.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BondTypeList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "bondTypeList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<BondTypeList> createBondTypeList(BondTypeList value) {
		return new JAXBElement<BondTypeList>(_BondTypeList_QNAME,
				BondTypeList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link AtomType }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "atomType", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<AtomType> createAtomType(AtomType value) {
		return new JAXBElement<AtomType>(_AtomType_QNAME, AtomType.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link AtomArray }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "atomArray", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<AtomArray> createAtomArray(AtomArray value) {
		return new JAXBElement<AtomArray>(_AtomArray_QNAME, AtomArray.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link AtomTypeList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "atomTypeList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<AtomTypeList> createAtomTypeList(AtomTypeList value) {
		return new JAXBElement<AtomTypeList>(_AtomTypeList_QNAME,
				AtomTypeList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Band }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "band", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Band> createBand(Band value) {
		return new JAXBElement<Band>(_Band_QNAME, Band.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Join }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "join", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Join> createJoin(Join value) {
		return new JAXBElement<Join>(_Join_QNAME, Join.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Action }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "action", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Action> createAction(Action value) {
		return new JAXBElement<Action>(_Action_QNAME, Action.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Electron }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "electron", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Electron> createElectron(Electron value) {
		return new JAXBElement<Electron>(_Electron_QNAME, Electron.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Property }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "property", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Property> createProperty(Property value) {
		return new JAXBElement<Property>(_Property_QNAME, Property.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link ReactionStepList }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "reactionStepList", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<ReactionStepList> createReactionStepList(
			ReactionStepList value) {
		return new JAXBElement<ReactionStepList>(_ReactionStepList_QNAME,
				ReactionStepList.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Metadata }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "metadata", substitutionHeadNamespace = "http://www.xml-cml.org/schema", substitutionHeadName = "anyCml")
	public JAXBElement<Metadata> createMetadata(Metadata value) {
		return new JAXBElement<Metadata>(_Metadata_QNAME, Metadata.class, null,
				value);
	}

}
