//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 10:54:28 PM EST 
//

//@javax.xml.bind.annotation.XmlSchema(elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.xml-cml.org/schema", xmlns = { @XmlNs(prefix = "", namespaceURI = "http://www.xml-cml.org/schema") }, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.xml_cml.schema;

import javax.xml.bind.annotation.XmlNs;

