//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 10:54:28 PM EST 
//

package org.xml_cml.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for reactionTypeType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="reactionTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="chainReaction"/>
 *     &lt;enumeration value="initiation"/>
 *     &lt;enumeration value="termination"/>
 *     &lt;enumeration value="reversible"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "reactionTypeType", namespace = "http://www.xml-cml.org/schema")
@XmlEnum
public enum ReactionTypeType {

	/**
	 * 
	 * 
	 * <pre>
	 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;h:div xmlns:h="http://www.w3.org/1999/xhtml" xmlns="http://www.xml-cml.org/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;h:p&gt;A reaction in which one or more reactive reaction intermediates (frequently
	 *                                         radicals) are continuously regenerated, usually through a repetitive cycle of
	 *                                         elementary steps (the 'propagation step') (IUPAC GoldBook).
	 *                                     &lt;/h:p&gt;
	 *                                 &lt;/h:div&gt;
	 * </pre>
	 * 
	 * 
	 * 
	 */
	@XmlEnumValue("chainReaction")
	CHAIN_REACTION("chainReaction"),

	/**
	 * 
	 * 
	 * <pre>
	 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;h:div xmlns:h="http://www.w3.org/1999/xhtml" xmlns="http://www.xml-cml.org/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;h:p&gt;
	 *                                         A reaction or process generating free radicals (or some other reactive
	 *                                         reaction intermediates) which then induce a chain reaction. For example,
	 *                                         in the chlorination of alkanes by a radical mechanism the initiation step is
	 *                                         the dissociation of molecular chlorine.
	 *                                         IUPAC Compendium of Chemical Terminology 2nd Edition (1997).
	 *                                     &lt;/h:p&gt;
	 *                                 &lt;/h:div&gt;
	 * </pre>
	 * 
	 * 
	 * 
	 */
	@XmlEnumValue("initiation")
	INITIATION("initiation"),

	/**
	 * 
	 * 
	 * <pre>
	 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;h:div xmlns:h="http://www.w3.org/1999/xhtml" xmlns="http://www.xml-cml.org/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;h:p&gt;
	 *                                         The steps in a chain reaction in which reactive intermediates are destroyed
	 *                                         or rendered inactive, thus ending the chain.
	 *                                         IUPAC Compendium of Chemical Terminology 2nd Edition (1997)
	 *                                         .
	 *                                     &lt;/h:p&gt;
	 *                                 &lt;/h:div&gt;
	 * </pre>
	 * 
	 * 
	 * 
	 */
	@XmlEnumValue("termination")
	TERMINATION("termination"),

	/**
	 * 
	 * 
	 * <pre>
	 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;h:div xmlns:h="http://www.w3.org/1999/xhtml" xmlns="http://www.xml-cml.org/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;h:p&gt;A reaction which can proceed in the forward direction as readily as in the
	 *                                         reverse direction (IUPAC GoldBook).
	 *                                     &lt;/h:p&gt;
	 *                                 &lt;/h:div&gt;
	 * </pre>
	 * 
	 * 
	 * 
	 */
	@XmlEnumValue("reversible")
	REVERSIBLE("reversible"),

	/**
	 * 
	 * 
	 * <pre>
	 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;h:div xmlns:h="http://www.w3.org/1999/xhtml" xmlns="http://www.xml-cml.org/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" class="summary"&gt;A value not in the controlled vocabulary - use dictRef to add further information.
	 *                                        &lt;/h:div&gt;
	 * </pre>
	 * 
	 * 
	 * 
	 */
	@XmlEnumValue("other")
	OTHER("other");
	private final String value;

	ReactionTypeType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static ReactionTypeType fromValue(String v) {
		for (ReactionTypeType c : ReactionTypeType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
