//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 10:54:28 PM EST 
//

package org.xml_cml.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for substanceListTypeType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="substanceListTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="solution"/>
 *     &lt;enumeration value="mixture"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "substanceListTypeType", namespace = "http://www.xml-cml.org/schema")
@XmlEnum
public enum SubstanceListTypeType {

	@XmlEnumValue("solution")
	SOLUTION("solution"), @XmlEnumValue("mixture")
	MIXTURE("mixture"), @XmlEnumValue("other")
	OTHER("other");
	private final String value;

	SubstanceListTypeType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static SubstanceListTypeType fromValue(String v) {
		for (SubstanceListTypeType c : SubstanceListTypeType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
